version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
      volumes: ./vaccinations_dump.sql:/var/lib/postgresql/data/vaccination_dump.sql
    ports:
      - 5432:5432
    networks:
      mynetwork:
        aliases:
          - db
  vaccinationusersservice:
    build:
      context: "./VaccinationUsersService"
      dockerfile: Dockerfile
    ports:
      - 80:8080
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: test
      DB_USERNAME: postgres
      DB_PASSWORD: root
      SERVER_PORT: 8080
      REMINDERS_MINUTES: 5
      SCAN_DB_MS: 60000
      SPRING_PROFILES_ACTIVE: prod
      AWS_ACCESS_KEY:
      AWS_SECRET_KEY:
    networks:
      - mynetwork

  notificationservice:
    build:
      context: "./NotificationService"
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      FIREBASE_TYPE: service_account
      FIREBASE_PROJECT_ID: notification-service-b1b97
      FIREBASE_PRIVATE_KEY_ID: 1d574db666b518ab1b9b847c4d5a0310ae9fc6d1
      FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCpbASSaDX8LjTu\n/bmuh2GYG9HxAfGQVmBTtNfHpkZDSXoXwcegnOGqe9j5+pU++tr5H9NbSCONje5N\njj0XN/JZGwrFkriRsg/B10Ml8Sesg3NpOoeaiMHtbPa4cdHvxNQRYErvRe98Cagw\ndckv/mYQ6VQnc07jwbmmeLX1CqBY7DNekuAns23yg8sYuBdV0DCs0pveG8i/LReY\nXtM3MOPxSAjFdvEhqD35sht+u6yYwEjnENKscadGdsBuv4gwxJlYn7yO0Fc21UkH\n9erTR0lNF3SeUml+rMB5aw4VKgDqBe7XP1qo50h/Oq9noWqBQXwVAqC2WPxJSNI7\nsW3KF8aPAgMBAAECggEABe6+myD1SFHPrLT2PDtsfeUSm19wfrRLKeM3CjxBbZv7\ngyyQ1hZL0Y4F/7WUnotKq6xcEakbd2G1KsKEjDxCZ5TRuUyDhgobSdBhcOWTXBPJ\n23hYGl+mPlnqOOZTbhODCnC54Mv0IjeRr3tlu3aA2Vj5avke6zCQVMrga1+Q/y+k\nB8YsHcWNmlQLlBHkmBjOnLCocqEv9+cZosJXKN6WbTEyflja3vvrRICWG0YR9Euh\nv70SCSk8MWPVb35O+PCBfe9W21fEzheyOm8lZYifT5m9c1yYJVCAZpwHYphDTi5n\nAR2iW5mpqs6A6hnsCaCz0hpugSOjsrIfr3P+Omf6IQKBgQDgtKbWysSTyVt67fmb\n93WewIlUUfzcXL9aT9Nkqb3DkDrv8mD0UGeCfdSyadR1pIYTqJee3PZmWcCq3wKp\nBd+O3BZrm+Iin5EhhnlTaJX4XwdlcQsoNqVtrLeTbVkYjlhp1RuxhVl8Rja7C57k\nW7/B6F5HAw4ZT71EJiHKxWvM6QKBgQDBBFsa8eePPFWKFkCtEopPRVY3cHjEjN9z\nQNAh3jEw3SOkCwJRUU0S/jLwuFHlKGfXHVZ5C9NnAXtXJ6aiHu4XLdYmPDAN6P2R\nZDsK3AcRS6Y9da7hSED9kt59Q2JIo99QKVv3b07XDYpkyUM1dSvxcHAGzY2gGu54\nw1IrfSZstwKBgG9HJ0RBgB4L3oC/Lxic8KOgh6G5RHbAe4a292HnaXFakMVZC8iR\ntOD7fYSpQizMQBWmLQfgNymykuZLsF6R6QcvWO8LcG5jBRVMKfMzXOl17gy/cZ4F\nieEJYpPg1/mALKqkfaVo+0q+3sW8WICQKyNU9rNGAQpp4bnJBH0NTXhZAoGBAIGN\n/+zNFCVDVRMTrqO8vxNIMf+SQa2D9PPyPAGPlyr6M9MHBK46SOaHsv96aJXNEi4E\nZidndaU9DGHKnoFRC3SJcqVFXufnTFPLmAnI+AF26oV0OUbDbcQGUcp4cT7ap6ix\nqiYiEyQr1YmiwbbfB/jOBJO8YuRlT03FpKDGJwVvAoGAASZhrJOkz00vgaEXCGf7\nevo/QbL2qGWcYU+CXPMM6bMUtDZUelJDKtq475Y82q8WEaZAjzx8m/X3f/6vC5Bm\n+Uzwh0MFJRt5L7WWKSjqeWhN1bmSqtsFkLOHprFtB/qHwaRpRQQo0NomIU+bWElT\nUPpF2L3qVELHUroVoG4F64k=\n-----END PRIVATE KEY-----\n"
      FIREBASE_CLIENT_EMAIL: firebase-adminsdk-tgiwx@notification-service-b1b97.iam.gserviceaccount.com
      FIREBASE_CLIENT_ID: 115358474262494970583
      FIREBASE_AUTH_URI: https://accounts.google.com/o/oauth2/auth
      FIREBASE_TOKEN_URI: https://oauth2.googleapis.com/token
      FIREBASE_AUTH_PROVIDER_X509_CERT_URL: https://www.googleapis.com/oauth2/v1/certs
      FIREBASE_CLIENT_X509_CERT_URL: https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-tgiwx%40notification-service-b1b97.iam.gserviceaccount.comdoi
      AWS_ACCESS_KEY:
      AWS_SECRET_KEY:
      SERVER_PORT: 8081
    networks:
      - mynetwork


networks:
  mynetwork: