spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop

  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: reminders