spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
        hibernate:
          default_schema: db
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: eu-north-1


server:
  port: ${SERVER_PORT}
reminder:
  getRemindersToBeSendInMinutes: ${REMINDERS_MINUTES}
  msToScanDb: ${SCAN_DB_MS}

