spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
  cloud:
    aws:
      credentials:
        access-key:
        secret-key:
      region:
        static: eu-north-1

server:
  port: 8080
reminder:
  getRemindersToBeSendInMinutes: 5
  msToScanDb: 60000