
spring:
  datasource:
    url: jdbc:mysql://localhost:8083/test
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop


  kafka:
    bootstrap-servers: localhost:29092
    template:
      default-topic: reminders
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8081

reminder:
  getRemindersToBeSendInMinutes: 5
  msToScanDb: 60000

