app:
  firebase-configuration-file: notification-service-b1b97-firebase-adminsdk-tgiwx-1d574db666.json

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-service
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value.default.type: "org.mwdziak.notificationservice.dto.ReminderMessage"
