spring:
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVERS}
      group-id: ${KAFKA_GROUP_ID}
      properties:
        spring:
          json:
            value.default.type: "org.mwdziak.notificationservice.dto.ReminderMessage"